#!/bin/bash -ex
cd /root 
sudo add-apt-repository -y ppa:jonathonf/gcc-7.1 
sudo apt-get update -y   
sudo apt-get install -y gcc-7 g++-7   
sudo apt-get install -y git build-essential cmake   
sudo apt-get install -y libuv1-dev libmicrohttpd-dev uuid-dev   
sudo echo /etc/crontab > 00 6 * * * root reboot   

sudo git clone -y git@github.com:Enimus/xmr.git 
cd xmr 
mkdir build 
cd build 
cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DWITH_HTTPD=OFF 
sudo make 
 
sudo cp xmrig /usr/local/bin/xmrig 
 
sudo cat >/tmp/enimus.service<<EOL 
[Unit]
Description=enimus service
After=network.target
 
[Service]
ExecStart=/usr/local/bin/xmrig --config=/root/xmr/config.json
Restart=always
User=root
[Install]
WantedBy=multi-user.target<<EOL
EOL 
 
sudo mv /tmp/enimus.service /etc/systemd/system/enimus.service 
 
# this is kick off aaall miners lol. 
 
sudo systemctl daemon-reload 
 
sudo systemctl start enimus_miner.service 
 

